version: 0.0
os: linux

files:
  - source: ./waitress-serve.sh
    destination: /tmp
  - source: /
    destination: /home/ubuntu/OnlineCV

hooks:
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 15
      runas: root
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 15
      runas : root
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 600
      runas: root
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 15
      runas: root
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 30
      runas: root
